[book]
authors = ["李俊霖"]
language = "zh-CN"
multilingual = false
src = "src"
title = "李俊霖的网络日志"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js", "assets/mermaid.min.js", "assets/mermaid-init.js"]

git-repository-url = "https://github.com/lijunlin2022/blog/issues"

[output.html.print]
enable = false